Description: WebACL WAFv2

Parameters:
  AlbArn:
    Type: String
    Description: "Arn of the Application loadbalancer to associate with WAF"
    Default: "no"
  NamePrefix:
    Type: String
    Description: "Name Prefix"
  AWSManagedRulesCommonRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesAdminProtectionRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesKnownBadInputsRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesSQLiRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesLinuxRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesUnixRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesWindowsRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesPHPRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesWordPressRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesAmazonIpReputationListEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesAnonymousIpListEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
  AWSManagedRulesCoreRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"

  DefaultActionAllowEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  OverrideActionCountCommonRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountAdminProtectionRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountKnownBadInputsRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountSQLiRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountLinuxRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountUnixRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountWindowsRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountPHPRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountWordPressRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountAmazonIpReputationListEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountAnonymousIpListEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"
  OverrideActionCountCoreRuleSetEnabled:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  CommonRuleSetExcludedRules:
    Type: String
    Default: ""
  AdminProtectionRuleSetExcludedRules:
    Type: String
    Default: ""
  KnownBadInputsRuleSetExcludedRules:
    Type: String
    Default: ""
  SQLiRuleSetExcludedRules:
    Type: String
    Default: ""
  LinuxRuleSetExcludedRules:
    Type: String
    Default: ""
  UnixRuleSetExcludedRules:
    Type: String
    Default: ""
  WindowsRuleSetExcludedRules:
    Type: String
    Default: ""
  PHPRuleSetExcludedRules:
    Type: String
    Default: ""
  WordPressRuleSetExcludedRules:
    Type: String
    Default: ""
  AmazonIpReputationListExcludedRules:
    Type: String
    Default: ""
  RulesAnonymousIpListExcludedRules:
    Type: String
    Default: ""
  CoreRuleSetExcludedRules:
    Type: String
    Default: ""

Conditions:
  IsAWSManagedRulesCommonRuleSetEnabled: !Equals [ !Ref AWSManagedRulesCommonRuleSetEnabled , "yes" ]
  IsAWSManagedRulesAdminProtectionRuleSetEnabled: !Equals [ !Ref AWSManagedRulesAdminProtectionRuleSetEnabled , "yes" ]
  IsAWSManagedRulesKnownBadInputsRuleSetEnabled: !Equals [ !Ref AWSManagedRulesKnownBadInputsRuleSetEnabled , "yes" ]
  IsAWSManagedRulesSQLiRuleSetEnabled: !Equals [ !Ref AWSManagedRulesSQLiRuleSetEnabled , "yes" ]
  IsAWSManagedRulesLinuxRuleSetEnabled: !Equals [ !Ref AWSManagedRulesLinuxRuleSetEnabled , "yes" ]
  IsAWSManagedRulesUnixRuleSetEnabled: !Equals [ !Ref AWSManagedRulesUnixRuleSetEnabled , "yes" ]
  IsAWSManagedRulesWindowsRuleSetEnabled: !Equals [ !Ref AWSManagedRulesWindowsRuleSetEnabled , "yes" ]
  IsAWSManagedRulesPHPRuleSetEnabled: !Equals [ !Ref AWSManagedRulesPHPRuleSetEnabled , "yes" ]
  IsAWSManagedRulesWordPressRuleSetEnabled: !Equals [ !Ref AWSManagedRulesWordPressRuleSetEnabled , "yes" ]
  IsAWSManagedRulesAmazonIpReputationListEnabled: !Equals [ !Ref AWSManagedRulesAmazonIpReputationListEnabled , "yes" ]
  IsAWSManagedRulesAnonymousIpListEnabled: !Equals [ !Ref AWSManagedRulesAnonymousIpListEnabled , "yes" ]
  IsAWSManagedRulesCoreRuleSetEnabled: !Equals [ !Ref AWSManagedRulesCoreRuleSetEnabled , "yes" ]

  IsDefaultActionAllowEnabled: !Equals [ !Ref DefaultActionAllowEnabled , "yes" ]

  IsOverrideActionCountCommonRuleSetEnabled: !Equals [ !Ref OverrideActionCountCommonRuleSetEnabled , "yes" ]
  IsOverrideActionCountAdminProtectionRuleSetEnabled: !Equals [ !Ref OverrideActionCountAdminProtectionRuleSetEnabled, "yes" ]
  IsOverrideActionCountKnownBadInputsRuleSetEnabled: !Equals [ !Ref OverrideActionCountKnownBadInputsRuleSetEnabled, "yes" ]
  IsOverrideActionCountSQLiRuleSetEnabled: !Equals [ !Ref OverrideActionCountSQLiRuleSetEnabled, "yes" ]
  IsOverrideActionCountLinuxRuleSetEnabled: !Equals [ !Ref OverrideActionCountLinuxRuleSetEnabled, "yes" ]
  IsOverrideActionCountUnixRuleSetEnabled: !Equals [ !Ref OverrideActionCountUnixRuleSetEnabled, "yes" ]
  IsOverrideActionCountWindowsRuleSetEnabled: !Equals [ !Ref OverrideActionCountWindowsRuleSetEnabled, "yes" ]
  IsOverrideActionCountPHPRuleSetEnabled: !Equals [ !Ref OverrideActionCountPHPRuleSetEnabled, "yes" ]
  IsOverrideActionCountWordPressRuleSetEnabled: !Equals [ !Ref OverrideActionCountWordPressRuleSetEnabled, "yes" ]
  IsOverrideActionCountAmazonIpReputationListEnabled: !Equals [ !Ref OverrideActionCountAmazonIpReputationListEnabled, "yes" ]
  IsOverrideActionCountAnonymousIpListEnabled: !Equals [ !Ref OverrideActionCountAnonymousIpListEnabled, "yes" ]
  IsOverrideActionCountCoreRuleSetEnabled: !Equals [ !Ref OverrideActionCountCoreRuleSetEnabled, "yes" ]

  IsCommonRuleSetExcludedRules: !Equals [ !Ref CommonRuleSetExcludedRules, "" ]
  IsAdminProtectionRuleSetExcludedRules: !Equals [ !Ref AdminProtectionRuleSetExcludedRules, "" ]
  IsKnownBadInputsRuleSetExcludedRules: !Equals [ !Ref KnownBadInputsRuleSetExcludedRules, "" ]
  IsSQLiRuleSetExcludedRules: !Equals [ !Ref SQLiRuleSetExcludedRules, "" ]
  IsLinuxRuleSetExcludedRules: !Equals [ !Ref LinuxRuleSetExcludedRules, "" ]
  IsUnixRuleSetExcludedRules: !Equals [ !Ref UnixRuleSetExcludedRules, "" ]
  IsWindowsRuleSetExcludedRules: !Equals [ !Ref WindowsRuleSetExcludedRules, "" ]
  IsPHPRuleSetExcludedRules: !Equals [ !Ref PHPRuleSetExcludedRules, "" ]
  IsWordPressRuleSetExcludedRules: !Equals [ !Ref WordPressRuleSetExcludedRules, "" ]
  IsAmazonIpReputationListExcludedRules: !Equals [ !Ref AmazonIpReputationListExcludedRules, "" ]
  IsRulesAnonymousIpListExcludedRules: !Equals [ !Ref RulesAnonymousIpListExcludedRules, "" ]
  IsCoreRuleSetExcludedRules: !Equals [ !Ref CoreRuleSetExcludedRules, "" ]

  IsAlbArnProvided: !Not [!Equals [ !Ref AlbArn, "no" ]]

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${NamePrefix}-WAFv2-WebACL"
      Scope: REGIONAL
      DefaultAction:
        'Fn::If':
          - IsDefaultActionAllowEnabled
          - Allow: {}
          - Block: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${NamePrefix}-WAFv2WebACLMetric"
      Rules:
        - Fn::If:
          - IsAWSManagedRulesCommonRuleSetEnabled
          -
            Name: AWSManagedRulesCommonRuleSet
            Priority: 0
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountCommonRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFCommonRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesCommonRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsCommonRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref CommonRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesAdminProtectionRuleSetEnabled
          -
            Name: AWSManagedRulesAdminProtectionRuleSet
            Priority: 1
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountAdminProtectionRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFAdminProtectionRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesAdminProtectionRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsAdminProtectionRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref AdminProtectionRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesKnownBadInputsRuleSetEnabled
          -
            Name: AWSManagedRulesKnownBadInputsRuleSet
            Priority: 2
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountKnownBadInputsRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFKnownBadInputsRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesKnownBadInputsRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsKnownBadInputsRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref KnownBadInputsRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesSQLiRuleSetEnabled
          -
            Name: AWSManagedRulesSQLiRuleSet
            Priority: 3
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountSQLiRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFSQLiRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesSQLiRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsSQLiRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref SQLiRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesLinuxRuleSetEnabled
          -
            Name: AWSManagedRulesLinuxRuleSet
            Priority: 4
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountLinuxRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFLinuxRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesLinuxRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsLinuxRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref LinuxRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesUnixRuleSetEnabled
          -
            Name: AWSManagedRulesUnixRuleSet
            Priority: 5
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountUnixRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFUnixRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesUnixRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsUnixRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref UnixRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesWindowsRuleSetEnabled
          -
            Name: AWSManagedRulesWindowsRuleSet
            Priority: 6
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountWindowsRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFWindowsRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesWindowsRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsWindowsRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref WindowsRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesPHPRuleSetEnabled
          -
            Name: AWSManagedRulesPHPRuleSet
            Priority: 7
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountPHPRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFPHPRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesPHPRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsPHPRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref PHPRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesWordPressRuleSetEnabled
          -
            Name: AWSManagedRulesWordPressRuleSet
            Priority: 8
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountWordPressRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFWordPressRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesWordPressRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsWordPressRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref WordPressRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesAmazonIpReputationListEnabled
          -
            Name: AWSManagedRulesAmazonIpReputationList
            Priority: 9
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountAmazonIpReputationListEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFAmazonIpReputationListMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesAmazonIpReputationList
                ExcludedRules:
                  'Fn::If':
                    - IsAmazonIpReputationListExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref AmazonIpReputationListExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesAnonymousIpListEnabled
          -
            Name: AWSManagedRulesAnonymousIpList
            Priority: 10
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountAnonymousIpListEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFAnonymousIpListMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesAnonymousIpList
                ExcludedRules:
                  'Fn::If':
                    - IsRulesAnonymousIpListExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref RulesAnonymousIpListExcludedRules ]
          - !Ref 'AWS::NoValue'
        - Fn::If:
          - IsAWSManagedRulesCoreRuleSetEnabled
          -
            Name: AWSManagedRulesCoreRuleSet
            Priority: 11
            OverrideAction:
              'Fn::If':
                - IsOverrideActionCountCoreRuleSetEnabled
                - Count: {}
                - None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub "${NamePrefix}-WAFCoreRuleSetMetric"
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesCoreRuleSet
                ExcludedRules:
                  'Fn::If':
                    - IsRulesCoreRuleSetExcludedRules
                    - []
                    - 'Fn::Split': [ ",", !Ref RulesCoreRuleSetExcludedRules ]
          - !Ref 'AWS::NoValue'

  WAFWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Condition: IsAlbArnProvided
    Properties:
      ResourceArn:
        Ref: AlbArn
      WebACLArn:
        Fn::GetAtt: [ WAFWebACL, Arn ]

Outputs:
  WAFWebName:
    Description: The name of the created WafWebACL
    Value: !Select [ 0, !Split ["|", !Ref WAFWebACL ]]
  WAFWebArn:
    Description: The ARN of the created WafWebACL
    Value: !GetAtt [ WAFWebACL, Arn ]
